### ISSUE TITLE
[BUG]使用Transition时出现问题

### ISSUE THREAD

**Issue by yhzcake** [PRO-2684/Transitio-user-css#13]
粘贴大段文字(不确定是不是大段文字,但是基本都是粘大段代码的时候出现)时,界面整体上移,只能重启qq解决
![image](https://github.com/user-attachments/assets/eef3a7ef-28a7-4316-82a1-fdc3b673436d)
正常状态
![image](https://github.com/user-attachments/assets/b5de305d-58d4-407d-ba97-6f60afbaf876)
不确定是否与其他插件有冲突,但是只开关这个css的时候确实关掉就没这个bug了

**Comment by PRO-2684** [comment]
刷新主界面是否可以解决此问题

**Comment by yhzcake** [comment]
Shortcutio的f5大刷新能解决,但是每次刷新重新加载很麻烦
是某个主题的问题..
但是那个主题作者应该是不会做任何其他插件适配...好麻烦
