### ISSUE TITLE
新功能 新建议

### ISSUE THREAD

**Issue by YatFanLan** [PRO-2684/Transitio-user-css#15]
1.[hide-items](https://github.com/PRO-2684/Transitio-user-css/blob/main/hide-items.css) 插件中的设置界面带 SVIP 的项目 (目前为超级调色盘) 屏蔽功能没有效果，希望设置界面带 SVIP 的项目 (目前为超级调色盘) 屏蔽功能单独提取出来。 因为可能会与轻量工具箱中的功能造成冲突。
2.希望给群聊群文件里边的群在线文档选项提供关闭按钮功能。(注：此功能包括但不限于在群聊>群应用>群文件 在内的所有界面)
![QQ_1724765538423](https://github.com/user-attachments/assets/bbba24f7-526a-4334-8de1-4a9e167e5fd4)
3.三大金刚键旁边的那个按钮
![QQ_1724805832686](https://github.com/user-attachments/assets/f21bdaa0-136e-4d47-9a33-1754b65237ce)

**Comment by PRO-2684** [comment]
1, 2: e8623e5335e34cddbbbb97ee4b3adbd39f3c9e4c
3: 我暂未升级新版本，故暂时不考虑适配

**Comment by YatFanLan** [comment]
> 1， 2： [e8623e5](https://github.com/PRO-2684/Transitio-user-css/commit/e8623e5335e34cddbbbb97ee4b3adbd39f3c9e4c) 3： 我暂未升级新版本，故暂时不考虑适配

屏蔽超级调色板功能 已经完美实现  感谢开发者 以及作者的付出
屏蔽群文件功能屏蔽之后页面布局不是很完美

**Comment by YatFanLan** [comment]
屏蔽设置界面的超级调色板功能 已经完美实现 感谢作者 以及开发者的付出
屏蔽群在线文档功能不甚完美 排序功能错位  应该是群在线文档功能的div没有完全去除 导致挤压了排序功能的div
以下是实现具体功能的CSS代码:
.file-manager-main .file-area > .file-area-list > .file-area-container > .file-area-container-list > .file-area-container-list-wrapper > .file-list-normal-container-wrapper > .file-list-scroll-outter > #file-manage-scroll-list > .group-file-banner {
    display: none; /* 隐藏文件管理器的群在线文档 */
}

**Comment by PRO-2684** [comment]
> 屏蔽设置界面的超级调色板功能 已经完美实现 感谢作者 以及开发者的付出 屏蔽群在线文档功能不甚完美 排序功能错位 应该是群在线文档功能的div没有完全去除 导致挤压了排序功能的div 以下是实现具体功能的CSS代码: ![QQ_1724815038320](https://private-user-images.githubusercontent.com/147362053/362107291-c02e80ea-35bc-4f99-aae6-2a5adc9879f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4OTI2NTYsIm5iZiI6MTcyNDg5MjM1NiwicGF0aCI6Ii8xNDczNjIwNTMvMzYyMTA3MjkxLWMwMmU4MGVhLTM1YmMtNGY5OS1hYWU2LTJhNWFkYzk4NzlmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwMDQ1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODA4ZjQzNmE1NTc4MjEzYzI4YTFhZWMwODg3NDk0MWE1MTc1Mjk2MWU4OWRiOWZmOTAxNTMxOGE5MDA5MzMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VPCD6_roUiTlxYlpHt3aqSbqy6RqszYGQERfeYCNO64)

已修复 d59d6cec931a053b5f103206d9b505475e5599ee

**Comment by YatFanLan** [comment]
https://github.com/PRO-2684/transitio/issues/4#issuecomment-2317300930
第四个功能已解决
但是不会通过 Issue 投稿  我就通过通过 Issue 投稿
希望作者可以添加进去 多谢作者
