### ISSUE TITLE
如何选中特定下拉框

### ISSUE THREAD

**Issue by YatFanLan** [PRO-2684/Transitio-user-css#20]
作者你好，我在使用你的https://github.com/PRO-2684/Transitio-user-css/#transparent CSS文件之后 发现可以通过该css文件中的某行代码调整下拉框的透明度。 我就打算在我的https://github.com/YatFanLan/Adjust-group-option-width-in-friend-info-interface CSS文件中加入调整好友分组界面的下拉框功能，但是当我实现了调整下拉框宽度功能的时候，发现别处也跟着变化了  所以我想请教一下，如何选中特定的某个下拉框？以达到预期效果！

**Comment by PRO-2684** [comment]
使用更为细致的 CSS 选择器即可

**Comment by YatFanLan** [comment]
使用层级选择器？

**Comment by PRO-2684** [comment]
> 使用层级选择器？

需要具体问题具体分析，通常来说优先考虑独具特点的元素 id, class 进行标识，然后再考虑祖先元素的特点

**Comment by YatFanLan** [comment]
> > 使用层级选择器？
> 
> 需要具体问题具体分析，通常来说优先考虑独具特点的元素 id, class 进行标识，然后再考虑祖先元素的特点

作者您好，我设置了好长时间，就是无法选中特定的下拉框。请问您是否有兴趣和我一起设置这个样式？
