### ISSUE TITLE
transparent 导致表情无法使用

### ISSUE THREAD

**Issue by aoguai** [PRO-2684/Transitio-user-css#22]
开启前效果：
正常显示，正常点击
![1](https://github.com/user-attachments/assets/f8f96f8e-0442-4100-a72e-17ba4add4eed)

开启后效果：
显示被遮挡，无法点击
![2](https://github.com/user-attachments/assets/472608f9-f5a3-4996-98d2-81dd02416b05)

运行环境：
Windows 10

QQNT版本：
9.9.16-28971 (64位)

LiteLoaderQQNT 版本：
1.2.2

Transitio 版本:
1.5.4

transparent 版本：
v0.1.2

**Comment by PRO-2684** [comment]
尝试将此文件最后“移除部分样式”的代码注释掉，是否可以解决此问题

**Comment by YatFanLan** [comment]
> 尝试将此文件最后“移除部分样式”的代码注释掉，是否可以解决此问题

无效果，  
.expression-panel, /* 表情面板 */ 这段代码注释掉有效果

**Comment by PRO-2684** [comment]
虽然不知道为什么，但是好像把 `.expression-panel` 改成 `.expression-panel > .sticker-panel-ref.expression-panel-inner > .sticker-panel` 就可以了。理论上来说就单纯改个透明度应该不会影响操作的，但是能跑就行（
