### ISSUE TITLE
新版中image-viewer 等一些似乎失效了

### ISSUE THREAD

**Issue by WhiteTiger-WT** [PRO-2684/Transitio-user-css#3]
![image](https://github.com/PRO-2684/Transitio-user-css/assets/59340574/4b6417c7-afa2-456b-98d5-95b645c26cc1)

**Comment by PRO-2684** [comment]
新版本结构变了，原来控制的按钮是悬浮在图片上的，现在是单独一栏不会阻挡图片，但是左右按钮应该还是生效的
