### ISSUE TITLE
请教一下，QQNT的各个元素在哪可以找到？

### ISSUE THREAD

**Issue by alrcatraz** [PRO-2684/Transitio-user-css#4]
想自定义一下文本字体和字号，并且移除气泡，但是找不到元素名，所以只能向大佬请教了！

**Comment by PRO-2684** [comment]
F12 打开开发者工具

**Comment by alrcatraz** [comment]
F12没什么反应啊？版本是9.9.7-20811

**Comment by PRO-2684** [comment]
> F12没什么反应啊？版本是9.9.7-20811

安装 https://github.com/mo-jinran/chii-devtools
